# Generated by Django 4.0.3 on 2022-03-26 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': 'Post Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='subcribe',
            options={'ordering': ['created_on'], 'verbose_name': 'Subcribe', 'verbose_name_plural': 'Subcribes'},
        ),
        migrations.AddField(
            model_name='subcribe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcribe',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
