# Generated by Django 4.0.3 on 2022-03-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
    ]
