# Generated by Django 4.0.3 on 2022-03-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_heading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribe',
            new_name='Subscribe',
        ),
    ]
