# Generated by Django 4.0.3 on 2022-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='postcategory',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='PostCategory/%Y/%m/%d/'),
        ),
    ]
