# Generated by Django 4.0.3 on 2022-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_contact_postcategory_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='PostTag/%Y/%m/%d/'),
        ),
    ]
