# Generated by Django 4.0.3 on 2022-04-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_resume_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Education', 'Education'), ('Experience', 'Experience'), ('Certification', 'Certification'), ('Awards', 'Awards')], max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'Resume Category',
                'verbose_name_plural': 'Resumes Categories',
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumecategory', to='user_profile.resumecategory'),
        ),
    ]
