# Generated by Django 4.0.3 on 2022-04-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_alter_resumecategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'Skills Category',
                'verbose_name_plural': 'Skills Categories',
            },
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='percentage',
            new_name='startdate',
        ),
        migrations.AlterField(
            model_name='skills',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skillscategory', to='user_profile.skillscategory'),
            preserve_default=False,
        ),
    ]
