# Generated by Django 4.0.3 on 2022-04-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_skillscategory_rename_percentage_skills_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='startdate',
            new_name='percentage',
        ),
    ]
