# Generated by Django 4.0.3 on 2022-04-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_alter_certification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='enddate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='awards',
            old_name='startdate',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='enddate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='startdate',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='enddate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='startdate',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='enddate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='startdate',
            new_name='start',
        ),
    ]
