# Generated by Django 4.0.3 on 2022-04-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Category',
            new_name='category',
        ),
    ]
