# Generated by Django 4.0.3 on 2022-04-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_resume_remove_certification_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='summery',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='mob',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='portfolio/mob/avatars/'),
        ),
    ]
