# Generated by Django 4.0.3 on 2022-04-21 09:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0028_rename_summary_resume_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Project',
        ),
    ]
